include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - use_super_parameters
    - directives_ordering
    - always_use_package_imports
    - unawaited_futures
    - prefer_final_locals
    # - avoid_print # Uncomment to disable the `avoid_print` rule
