import 'package:vanholst/src/features/logbook/domain/logbook_entry.dart';

/// Test products to be used until a data source is implemented
const kTestLogbook = [
  LogbookEntry(
    userId: "122",
    id: "6064",
    infoForCoach: null,
    date: "11/06/2024",
    shortDayName: "di",
    program: "",
    sleep: "8.0",
    timings: null,
    performance:
        "Ging prima.",
    circumstances: null,
    km: "5.8",
    link:
        "<a href='https://connect.garmin.com/modern/activity/88888888888' rel='nofollow' target='_blank'><button class=''>GPS</button></a>",
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6067",
    infoForCoach: null,
    date: "12/06/2024",
    shortDayName: "wo",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6070",
    infoForCoach: null,
    date: "13/06/2024",
    shortDayName: "do",
    program: "wandel 10min - 3x6min T5,30 p2min wandel 10min wandel",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6073",
    infoForCoach: null,
    date: "14/06/2024",
    shortDayName: "vr",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6076",
    infoForCoach: null,
    date: "15/06/2024",
    shortDayName: "za",
    program:
        "fietsen 90-120min (voorkeur sportfiets of iig fiets met versnellingen, anders gewone) cadans relatief hoog houden",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6079",
    infoForCoach: null,
    date: "16/06/2024",
    shortDayName: "zo",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6082",
    infoForCoach: null,
    date: "17/06/2024",
    shortDayName: "ma",
    program: "wandel 10min - 2x10min T5,30->5,20 p3min wandel 10min wandel",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6085",
    infoForCoach: null,
    date: "18/06/2024",
    shortDayName: "di",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6088",
    infoForCoach: null,
    date: "19/06/2024",
    shortDayName: "wo",
    program: "wandel 10min - 20min T5,30 10min wandel",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6091",
    infoForCoach: null,
    date: "20/06/2024",
    shortDayName: "do",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6094",
    infoForCoach: null,
    date: "21/06/2024",
    shortDayName: "vr",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6097",
    infoForCoach: null,
    date: "22/06/2024",
    shortDayName: "za",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6100",
    infoForCoach: null,
    date: "23/06/2024",
    shortDayName: "zo",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6103",
    infoForCoach: null,
    date: "24/06/2024",
    shortDayName: "ma",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6106",
    infoForCoach: null,
    date: "25/06/2024",
    shortDayName: "di",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6109",
    infoForCoach: null,
    date: "26/06/2024",
    shortDayName: "wo",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6112",
    infoForCoach: null,
    date: "27/06/2024",
    shortDayName: "do",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6115",
    infoForCoach: null,
    date: "28/06/2024",
    shortDayName: "vr",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6118",
    infoForCoach: null,
    date: "29/06/2024",
    shortDayName: "za",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6121",
    infoForCoach: null,
    date: "30/06/2024",
    shortDayName: "zo",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
  LogbookEntry(
    userId: "122",
    id: "6124",
    infoForCoach: null,
    date: "01/07/2024",
    shortDayName: "ma",
    program: "",
    sleep: null,
    timings: null,
    performance: null,
    circumstances: null,
    km: "",
    link: null,
    feedbackCoach: null,
  ),
];
