import 'package:vanholst/src/localization/string_hardcoded.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

class NotLoggedInException extends AppException {
  NotLoggedInException()
      : super('not-logged-in', 'User is not logged in'.hardcoded);
}

class WrongPasswordException extends AppException {
  WrongPasswordException()
      : super('wrong-password', 'Wrong password'.hardcoded);
}

class UserNotFoundException extends AppException {
  UserNotFoundException() : super('user-not-found', 'User not found'.hardcoded);
}

class PageLoadException extends AppException {
  PageLoadException()
      : super('page-load-error', "Page didn't load correctly".hardcoded);
}

class MissingCookiesException extends AppException {
  MissingCookiesException()
      : super('missing-cookies', 'No cookies in response'.hardcoded);
}

class ParseException extends AppException {
  ParseException()
      : super('parse-error', 'Error parsing the response'.hardcoded);
}
